import type { Profile, LeetCodeStats, Project } from "../types";

export const FALLBACK_PROFILE: Profile = {
  name: "Divy Makwana",
  role: "MCA Student · Full-stack & AI/ML Developer",
  title: "Full-stack & AI/ML Developer",
  tagline: "Building full-stack apps and AI/ML dashboards that turn data into clear decisions",
  location: "Ahmedabad, Gujarat, India",
  status: "Open to internships / opportunities",
  email: "divymakwana375@gmail.com",
  resume_drive_url:
    "https://drive.google.com/file/d/1quRrPeAvFvs2sSuZMzze2EcbODkOqdm2/view?usp=sharing",
  resume_pdf: "/DivyMakwana.pdf",
  socials: {
    github: "https://github.com/divy1105",
    linkedin: "https://www.linkedin.com/in/divy-makwana-89863227a/",
    leetcode: null,
    geeksforgeeks: null,
  },
  about: [
    "I'm Divy Makwana, an MCA student at GLS University with a BCA background from Lokmanya College of Computer Application. I care about shipping practical software — not just demos — across Python, FastAPI/Flask, React, and .NET.",
    "I build full-stack products and ML-backed tools: career matching (CareerLens), AI task extraction from meeting notes, event management systems, and crime-forecast dashboards with maps and live analytics.",
    "I'm currently a Data Science Trainee at QSpiders Ahmedabad and looking for internships or entry-level roles where I can contribute to product engineering and applied ML.",
  ],
  facts: [
    { label: "Current", value: "Data Science Trainee" },
    { label: "Based in", value: "Ahmedabad, IN" },
    { label: "Highlight", value: "CareerLens" },
  ],
  education: [
    {
      degree: "MCA",
      institution: "GLS University",
      start: "2024",
      end: "2026",
      score: "CGPA 7.66",
    },
    {
      degree: "BCA",
      institution: "Lokmanya College of Computer Application",
      start: "2021",
      end: "2024",
      score: "CGPA 7.63",
    },
  ],
  achievements: [
    "3rd place — CTF @ GLS",
    "Build with Gemma: Ahmedabad (limited-seat workshop)",
    "SIH 2025 participant",
    "Odoo × Parul University 2025",
    "Cursor Ahmedabad Hackathon",
    "ISRO Bharatiya Antariksh Hackathon",
    "EY Techathon 6.0",
    "Gen AI Exchange 2025",
  ],
  experience: [
    {
      role: "Data Science Trainee",
      company: "QSpiders Ahmedabad",
      location: "Ahmedabad",
      start: "December 2025",
      end: "Present",
      current: true,
      highlights: [
        "Practiced end-to-end data workflows: cleaning, EDA, and model evaluation on real training datasets",
        "Built Python analysis and visualization pipelines using pandas and related ML tooling",
        "Applied supervised ML concepts (feature prep, train/test split, metrics) to structured prediction problems",
      ],
    },
  ],
  skills: {
    Languages: ["Python", "JavaScript / TypeScript", "C# / .NET", "HTML / CSS"],
    "Backend / APIs": ["FastAPI", "Flask", "Hono", "ASP.NET", "EF Core"],
    Frontend: [
      "React",
      "React Native",
      "Vite",
      "Tailwind CSS",
      "Ant Design",
      "TanStack Router / Query",
      "Framer Motion",
      "Chart.js",
      "Leaflet",
    ],
    Databases: ["SQLite", "PostgreSQL (Neon)", "MySQL", "MongoDB"],
    "Data / ML / AI": ["pandas", "scikit-learn", "LightGBM", "Groq API", "Google Gemini"],
    Concepts: ["Machine Learning", "DBMS", "OOP", "REST APIs"],
  },
  contact_invite: "Have an opportunity or project? My inbox is open.",
};

export const FALLBACK_LEETCODE: LeetCodeStats = {
  username: null,
  ranking: null,
  totalSolved: 0,
  easySolved: 0,
  mediumSolved: 0,
  hardSolved: 0,
  reputation: 0,
  contestRating: null,
  contestsAttended: 0,
  topContests: [],
  source: "fallback",
};

export const FALLBACK_PROJECTS: Project[] = [
  {
    id: "seed-0",
    title: "CrimePulse",
    description: "Chicago crime awareness dashboard with live 90-day beat forecasts",
    content_html: `<h1>CrimePulse</h1><p>Chicago crime awareness dashboard with <strong>live 90-day beat forecasts</strong>.</p><h2>Overview</h2><p>CrimePulse helps explore recent crime patterns and projected activity across police beats. It pairs a Flask backend with LightGBM forecasting and an interactive map + chart frontend.</p><h2>Highlights</h2><ul><li>MAE <strong>1.06</strong> on forecast evaluation</li><li>Coverage across <strong>305</strong> beats</li><li>Live forecast window for the next 90 days</li></ul><h2>Stack</h2><ul><li>Python &amp; Flask</li><li>LightGBM</li><li>Chart.js &amp; Leaflet</li><li>SQLite</li></ul><h2>Status</h2><p>Public GitHub link coming soon — details shown here until the repo is published.</p>`,
    tech: ["Python", "Flask", "LightGBM", "Chart.js", "Leaflet", "SQLite"],
    github_url: null,
    demo_url: null,
    featured: true,
    order: 1,
    source: "manual",
  },
  {
    id: "seed-1",
    title: "CareerLens",
    description: "AI resume-to-career platform — job match, skill gaps, roadmap, mock interviews",
    tech: ["React", "Vite", "Tailwind", "FastAPI", "Gemini", "Exa"],
    github_url: "https://github.com/divy1105/CareerLens",
    demo_url: null,
    featured: true,
    order: 2,
    source: "manual",
  },
  {
    id: "seed-5",
    title: "TravelMind",
    description:
      "Plan multi-city trips as one story — itinerary, budget, packing, and notes in one place",
    tech: ["React", "TypeScript", "Vite", "Hono", "Neon Postgres", "Tailwind"],
    github_url: "https://github.com/divy1105/TravelMind",
    demo_url: null,
    featured: true,
    order: 3,
    source: "manual",
  },
  {
    id: "seed-2",
    title: "Manager_Task_Ai",
    description: "Turn meeting notes into structured tasks with AI extraction",
    tech: ["FastAPI", "React", "Vite", "Neon Postgres", "Groq API"],
    github_url: "https://github.com/divy1105/Manager_Task_Ai",
    demo_url: null,
    featured: true,
    order: 4,
    source: "manual",
  },
  {
    id: "seed-3",
    title: "Event-Management-System-MCA",
    description: "MCA final-year event management portal (.NET + React)",
    content_html: `<h1>Event Management System</h1><p>MCA final-year event management portal — organize events with a modern web client and .NET API.</p><h2>Features</h2><ul><li>Event creation and organization workflows</li><li>Modern React + Ant Design client</li><li>ASP.NET API with TypeScript frontend tooling</li></ul><h2>Stack</h2><p>C# / ASP.NET, React, TypeScript, Vite, Ant Design</p><h2>Repository</h2><p><a href="https://github.com/divy1105/Event-Management-System-MCA">github.com/divy1105/Event-Management-System-MCA</a></p>`,
    tech: ["C# / ASP.NET", "React", "TypeScript", "Vite", "Ant Design"],
    github_url: "https://github.com/divy1105/Event-Management-System-MCA",
    demo_url: null,
    featured: false,
    order: 5,
    source: "manual",
  },
  {
    id: "seed-4",
    title: "Sporties",
    description: "E-commerce for sports equipment — catalog, cart, checkout",
    content_html: `<h1>Sporties</h1><p>Full-stack e-commerce platform for sports equipment with product catalog, cart, and checkout flow.</p><h2>Features</h2><ul><li>Product catalog browsing</li><li>Shopping cart</li><li>Checkout flow backed by MySQL</li></ul><h2>Stack</h2><p>HTML, CSS, JavaScript, PHP, MySQL (XAMPP)</p><h2>Status</h2><p>Public GitHub link coming soon — project details shown here until published.</p>`,
    tech: ["HTML", "CSS", "JavaScript", "PHP", "MySQL"],
    github_url: null,
    demo_url: null,
    featured: false,
    order: 6,
    source: "manual",
  },
];
